server:
  port: 8081
spring:
  profiles:
    active: default
  datasource:
    url: jdbc:postgresql://db:5432/MoviePortal
    driver-class-name: org.postgresql.Driver
    password: postgres
    username: postgres
  session:
    timeout: 86400
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
  application:
    name: "Movie Review Portal"
logging:
  pattern:
    console: "%green(%d{HH:mm:ss}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n"
  level:
    org.springframework.security: TRACE
    org.springframework.cache: DEBUG
    com.github.benmanes.caffeine: DEBUG
    pl.patrykkukula.MovieReviewPortal: DEBUG
Jwt:
  secret: ${SECRET_KEY}