server:
  port: 8081
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/MoviePortal
    driver-class-name: org.postgresql.Driver
    password: Patryk
    username: postgres
  jpa:
    hibernate:
      ddl-auto: create
    defer-datasource-initialization: true
  sql:
    init:
      mode: always
logging:
  pattern:
    console: "%green(%d{HH:mm:ss}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n"
  level:
    org.springframework.security: TRACE