server:
  port: 8081
spring:
  config:
    activate:
      on-profile: qa
  session:
    timeout: 86400
  datasource:
    url: jdbc:postgresql://localhost:5432/MoviePortal
    driver-class-name: org.postgresql.Driver
    password: ${DATASOURCE_PASSWORD}
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  sql:
    init:
      mode: always
  application:
    name: "Movie Review Portal - QA profile"
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    default-encoding: UTF-8
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            trust: smtp.gmail.com
          ssl:
            enable: false
          connectiontimeout: 10000
          timeout: 10000
          writetimeout: 10000
app:
  mail:
    from: "Movie portal <movieportalapp@gmail.com>"
logging:
  pattern:
    console: "%green(%d{HH:mm:ss}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %msg%n"
  level:
    org.springframework.security: TRACE
    org.springframework.cache: DEBUG
    com.github.benmanes.caffeine: DEBUG
    pl.patrykkukula.MovieReviewPortal: DEBUG